#!/bin/sh

PSQL="psql -h $PG_HOST -d $PG_DB -U $PG_USER -tf"

DIR=$(dirname "$0")

echo "Directory is $DIR"

$PSQL "$DIR/pending-feeds.sql"   \
  | nodejs                       \
      "$DIR/gs-feeds.js"    \
  | tee "$DIR/news.csv"          \
  | $PSQL "$DIR/import-news.sql"

#      --web-host 0.0.0.0         \
